# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2

defaults: &defaults
  working_directory: ~

jobs:
  "style":
    docker:
      - image: testthedocs/ttd-vale
    <<: *defaults
    steps:
      - checkout
      - run: vale Content/*.md