version: 2

defaults: &defaults
  working_directory: ~/Content

jobs:
  "style":
    docker:
      - image: testthedocs/ttd-vale
    <<: *defaults
    steps:
      - checkout
      - run: vale --no-exit --config='/srv/.vale.ini' **/*.md

workflows:
  version: 2
  ttd:
    jobs:
      - "style"