# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2

jobs:
  "style":
    docker:
      - image: testthedocs/ttd-vale
    steps:
      - checkout
      - command: /Content:/srv/tests

workflows:
  version: 2
  ttd:
    jobs:
      - "style"


      # docker run -it -v `pwd`:/srv/tests testthedocs/ttd-vale
